# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1rflrslxhxlwxrynd2f53d7msywzcfjhqldqsnwpk7ngaszyrwc6";
    aarch64-linux = "1ijfd4lh8p0cipvs25kgxsn7k4apmpwlgwx7r70q1j21qgp030fz";
    x86_64-darwin = "16q4x9lhmp4hxkmpwhv5vy3w95ghzf5havdz8lfzs9jgj2hcs9a6";
    aarch64-darwin = "08pvvjgjq4da6m0yg1vgivrjl0jx4zgqk86ndilydv5h9viix65h";
  };

  urlMap = {
    x86_64-linux = "https://github.com/shopware/shopware-cli/releases/download/0.15.0/shopware-cli_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/shopware/shopware-cli/releases/download/0.15.0/shopware-cli_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/shopware/shopware-cli/releases/download/0.15.0/shopware-cli_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/shopware/shopware-cli/releases/download/0.15.0/shopware-cli_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "shopware-cli";
  version = "0.15.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./shopware-cli $out/bin/shopware-cli
  '';
  postInstall = ''
    installShellCompletion --cmd shopware-cli \
    --bash <($out/bin/shopware-cli completion bash) \
    --zsh <($out/bin/shopware-cli completion zsh) \
    --fish <($out/bin/shopware-cli completion fish)
  '';

  meta = {
    description = "Command line tool for Shopware 6";
    homepage = "https://sw-cli.fos.gg";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
